[package]
name = "engine_derive"
version = "0.1.0"
authors = ["Cristi Cobzarenco <cristi.cobzarenco@gmail.com>"]
edition = "2018"

[lib]
proc-macro = true

[dependencies]
syn = "1.0.68"
quote = "1.0.9"
proc-macro2 = "1.0.26"
